In [38]:
#import pandas
import pandas as pd

In [39]:
# read csv in
df = pd.read_csv('../data/SocialDistancing311_05102020.csv')
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,46162421,05/10/2020 01:39:26 AM,05/10/2020 01:51:06 AM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10013.0,355 WEST BROADWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.722951,-74.003272,"(40.7229507643479, -74.003272178444)"
1,46162939,05/09/2020 01:39:40 PM,05/09/2020 01:55:27 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,10029.0,1776 LEXINGTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.795072,-73.944226,"(40.79507193158142, -73.94422602045823)"
2,46162411,05/09/2020 12:30:09 PM,05/09/2020 12:47:45 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11226.0,1887 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.639548,-73.948356,"(40.63954753440908, -73.94835554992862)"
3,46164818,05/09/2020 08:28:54 PM,05/09/2020 09:44:36 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11432.0,171-16 HILLSIDE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.711502,-73.790797,"(40.71150171192844, -73.79079670500467)"
4,46164817,05/09/2020 10:14:17 PM,05/09/2020 10:37:13 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10467.0,2228 WHITE PLAINS ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.858432,-73.867556,"(40.85843153130007, -73.86755561818842)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31501,45914663,03/29/2020 12:17:15 PM,03/29/2020 02:46:21 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10452.0,125 EAST 170 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.839395,-73.915512,"(40.839395420668026, -73.91551169359307)"
31502,45912725,03/29/2020 12:09:53 PM,03/29/2020 01:18:27 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11204.0,5312 16 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.628689,-73.987967,"(40.628689142504065, -73.98796732089522)"
31503,45912069,03/29/2020 10:26:40 PM,03/29/2020 10:37:01 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11218.0,4307 18 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.631166,-73.976258,"(40.63116586530841, -73.97625799437061)"
31504,45914171,03/29/2020 08:01:48 PM,03/29/2020 09:33:30 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10040.0,4441 BROADWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.856888,-73.932552,"(40.85688767546475, -73.93255208623478)"
31505,45912062,03/29/2020 04:15:20 PM,03/29/2020 04:58:15 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11385.0,89-89 UNION TURNPIKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.706649,-73.855143,"(40.70664910607482, -73.85514316099588)"

In [40]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,46162421,05/10/2020 01:39:26 AM,05/10/2020 01:51:06 AM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10013.0,355 WEST BROADWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.722951,-74.003272,"(40.7229507643479, -74.003272178444)"
1,46162939,05/09/2020 01:39:40 PM,05/09/2020 01:55:27 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,10029.0,1776 LEXINGTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.795072,-73.944226,"(40.79507193158142, -73.94422602045823)"
2,46162411,05/09/2020 12:30:09 PM,05/09/2020 12:47:45 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11226.0,1887 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.639548,-73.948356,"(40.63954753440908, -73.94835554992862)"
3,46164818,05/09/2020 08:28:54 PM,05/09/2020 09:44:36 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11432.0,171-16 HILLSIDE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.711502,-73.790797,"(40.71150171192844, -73.79079670500467)"
4,46164817,05/09/2020 10:14:17 PM,05/09/2020 10:37:13 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10467.0,2228 WHITE PLAINS ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.858432,-73.867556,"(40.85843153130007, -73.86755561818842)"

In [41]:
# reveal each column header
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31506 entries, 0 to 31505
Data columns (total 41 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unique Key                      31506 non-null  int64
 1   Created Date                    31506 non-null  object
 2   Closed Date                     31447 non-null  object
 3   Agency                          31506 non-null  object
 4   Agency Name                     31506 non-null  object
 5   Complaint Type                  31506 non-null  object
 6   Descriptor                      31506 non-null  object
 7   Location Type                   26478 non-null  object
 8   Incident Zip                    31504 non-null  float64
 9   Incident Address                31505 non-null  object
 10  Street Name                     31505 non-null  object
 11  Cross Street 1                  31468 non-null  object
 12  Cross Street 2                  31474 non-null  object
 13  Intersection Street 1           31468 non-null  object
 14  Intersection Street 2           31474 non-null  object
 15  Address Type                    0 non-null      float64
 16  City                            28094 non-null  object
 17  Landmark                        28094 non-null  object
 18  Facility Type                   0 non-null      float64
 19  Status                          31506 non-null  object
 20  Due Date                        0 non-null      float64
 21  Resolution Description          31448 non-null  object
 22  Resolution Action Updated Date  31458 non-null  object
 23  Community Board                 31506 non-null  object
 24  BBL                             26717 non-null  float64
 25  Borough                         31506 non-null  object
 26  X Coordinate (State Plane)      31157 non-null  float64
 27  Y Coordinate (State Plane)      31157 non-null  float64
 28  Open Data Channel Type          31506 non-null  object
 29  Park Facility Name              31506 non-null  object
 30  Park Borough                    31506 non-null  object
 31  Vehicle Type                    0 non-null      float64
 32  Taxi Company Borough            0 non-null      float64
 33  Taxi Pick Up Location           0 non-null      float64
 34  Bridge Highway Name             0 non-null      float64
 35  Bridge Highway Direction        0 non-null      float64
 36  Road Ramp                       0 non-null      float64
 37  Bridge Highway Segment          0 non-null      float64
 38  Latitude                        31157 non-null  float64
 39  Longitude                       31157 non-null  float64
 40  Location                        31157 non-null  object
dtypes: float64(16), int64(1), object(24)
memory usage: 9.9+ MB

In [43]:
# Fill all null values with "" and clean all non-perfect integers in 'affected' column
df = df.fillna("")

In [44]:
# Find out which buroughs have the most complaints
df['Community Board'].value_counts().reset_index()

                        index  Community Board
0                 01 BROOKLYN             1336
1                   01 QUEENS             1131
2                12 MANHATTAN             1116
3                03 MANHATTAN              924
4                 12 BROOKLYN              876
..                        ...              ...
72                56 BROOKLYN                9
73                  80 QUEENS                7
74              0 Unspecified                5
75                   27 BRONX                5
76  Unspecified STATEN ISLAND                4

[77 rows x 2 columns]

In [45]:
# Find out the location types where most of these incidents are occuring
location_complaints = df['Location Type'].value_counts().reset_index()
location_complaints

                        index  Location Type
0            Store/Commercial           9675
1  Residential Building/House           7263
2             Street/Sidewalk           6144
3                                       5028
4             Park/Playground           3396

In [46]:
#Export dataset to csv with code below
#location_complaints.to_csv('../output/Social_Distancing_Complaints_by_location.csv', index=False)

In [47]:
# Find out what was the status on complaints and how the NYPD handled it.
df['Resolution Description'].value_counts()

The Police Department responded to the complaint and took action to fix the condition.                                                                                                       14729
The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.                                                       7875
The Police Department responded to the complaint and determined that police action was not necessary.                                                                                         6135
The Police Department responded and upon arrival those responsible for the condition were gone.                                                                                               1482
The Police Department reviewed your complaint and provided additional information below.                                                                                                       348
The Police Department responded to the complaint but officers were unable to gain entry into the premises.                                                                                     340
This complaint does not fall under the Police Department's jurisdiction.                                                                                                                       265
Your request can not be processed at this time because of insufficient contact information. Please create a new Service Request on NYC.gov and provide more detailed contact information.      116
The Police Department responded to the complaint and a report was prepared.                                                                                                                     85
                                                                                                                                                                                                58
The Police Department issued a summons in response to the complaint.                                                                                                                            56
The Police Department made an arrest in response to the complaint.                                                                                                                              15
Your complaint has been received by the Police Department and additional information will be available later.                                                                                    2
Name: Resolution Description, dtype: int64

Out of 31,506 complaints as of 5/10, only 15 arrests were made.

In [48]:
# Where were the arrests made? "The Police Department made an arrest in response to the complaint."
# resolution_desc = df.groupby(["Incident Address", "Community Board", "Resolution Description"])["Resolution Description"].count().reset_index(name='count').sort_values(['count'], ascending=False)
# resolution_desc

In [49]:
# Isolate the resolution results by only those who were arrested as a result of the complaints.
nypd_resolve = 'The Police Department made an arrest in response to the complaint.'
nypd_resolve

'The Police Department made an arrest in response to the complaint.'

In [50]:
# Filter only the social distancing complaints where an arrest was made.
nypd_arrests = df[df["Resolution Description"] == nypd_resolve]
nypd_arrests

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
2480,46134182,05/05/2020 04:23:11 PM,05/06/2020 09:49:07 AM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,10014,65 GANSEVOORT STREET,...,,,,,,,,40.7394,-74.0073,"(40.73939714807013, -74.00734707805555)"
4491,46116030,05/03/2020 04:19:37 PM,05/03/2020 04:40:35 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11225,474 BROOKLYN AVENUE,...,,,,,,,,40.6632,-73.9456,"(40.66318981146139, -73.94557262281035)"
7161,46108213,05/02/2020 01:40:10 PM,05/02/2020 01:54:19 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Residential Building/House,11221,165 VAN BUREN STREET,...,,,,,,,,40.6905,-73.9391,"(40.6905437358996, -73.93909565939045)"
8433,46092829,04/29/2020 09:28:59 PM,04/29/2020 09:58:05 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,10036,306 WEST 44 STREET,...,,,,,,,,40.7588,-73.9894,"(40.75875560213712, -73.98939489743731)"
11348,46065834,04/25/2020 09:34:00 PM,04/25/2020 10:26:10 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11233,1790 STERLING PLACE,...,,,,,,,,40.6708,-73.9195,"(40.670846184164645, -73.91951032625433)"
11813,46064207,04/25/2020 10:36:56 PM,04/25/2020 10:55:42 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Store/Commercial,11233,1435 HERKIMER STREET,...,,,,,,,,40.6773,-73.9059,"(40.67725587512683, -73.90588205457627)"
12392,46064972,04/25/2020 09:32:42 PM,04/25/2020 10:27:03 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11233,1790 STERLING PLACE,...,,,,,,,,40.6708,-73.9195,"(40.670846184164645, -73.91951032625433)"
13281,46050100,04/23/2020 07:11:49 PM,04/23/2020 08:08:56 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Residential Building/House,10026,65 LENOX AVENUE,...,,,,,,,,40.8004,-73.9509,"(40.800383269350185, -73.95089273331729)"
15482,46032986,04/20/2020 05:03:02 PM,04/20/2020 05:48:48 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,10040,9 THAYER STREET,...,,,,,,,,40.8617,-73.926,"(40.861749992284324, -73.92596744617518)"
17802,46020059,04/19/2020 12:48:48 AM,04/19/2020 03:12:25 AM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Residential Building/House,10472,1052 WARD AVENUE,...,,,,,,,,40.8252,-73.8765,"(40.82523042151155, -73.87647053467457)"
26046,45988910,04/12/2020 05:39:16 PM,04/12/2020 06:37:22 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11102,14-04 ASTORIA PARK SOUTH,...,,,,,,,,40.7763,-73.9272,"(40.77634607575273, -73.92717084567728)"
28990,45952221,04/06/2020 09:20:55 PM,04/06/2020 11:08:47 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Park/Playground,11249,BERRY PLAYGROUND,...,,,,,,,,40.7127,-73.9635,"(40.71265492845909, -73.96352823954949)"
29097,45957873,04/06/2020 04:11:16 PM,04/06/2020 07:54:19 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11249,SOUTH 3 STREET,...,,,,,,,,,,
29160,45957221,04/06/2020 06:52:05 PM,04/06/2020 07:55:19 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,Street/Sidewalk,11211,180 SOUTH 3 STREET,...,,,,,,,,40.7118,-73.9606,"(40.71179209572227, -73.96056368337936)"
29277,45954706,04/06/2020 06:23:20 PM,04/06/2020 09:12:28 PM,NYPD,New York City Police Department,Non-Emergency Police Matter,Social Distancing,,11211,BEDFORD AVENUE,...,,,,,,,,40.7125,-73.9626,"(40.71252561081519, -73.96255077806624)"

In [51]:
nypd_arrests.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 2480 to 29277
Data columns (total 41 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unique Key                      15 non-null     int64
 1   Created Date                    15 non-null     object
 2   Closed Date                     15 non-null     object
 3   Agency                          15 non-null     object
 4   Agency Name                     15 non-null     object
 5   Complaint Type                  15 non-null     object
 6   Descriptor                      15 non-null     object
 7   Location Type                   15 non-null     object
 8   Incident Zip                    15 non-null     object
 9   Incident Address                15 non-null     object
 10  Street Name                     15 non-null     object
 11  Cross Street 1                  15 non-null     object
 12  Cross Street 2                  15 non-null     object
 13  Intersection Street 1           15 non-null     object
 14  Intersection Street 2           15 non-null     object
 15  Address Type                    15 non-null     object
 16  City                            15 non-null     object
 17  Landmark                        15 non-null     object
 18  Facility Type                   15 non-null     object
 19  Status                          15 non-null     object
 20  Due Date                        15 non-null     object
 21  Resolution Description          15 non-null     object
 22  Resolution Action Updated Date  15 non-null     object
 23  Community Board                 15 non-null     object
 24  BBL                             15 non-null     object
 25  Borough                         15 non-null     object
 26  X Coordinate (State Plane)      15 non-null     object
 27  Y Coordinate (State Plane)      15 non-null     object
 28  Open Data Channel Type          15 non-null     object
 29  Park Facility Name              15 non-null     object
 30  Park Borough                    15 non-null     object
 31  Vehicle Type                    15 non-null     object
 32  Taxi Company Borough            15 non-null     object
 33  Taxi Pick Up Location           15 non-null     object
 34  Bridge Highway Name             15 non-null     object
 35  Bridge Highway Direction        15 non-null     object
 36  Road Ramp                       15 non-null     object
 37  Bridge Highway Segment          15 non-null     object
 38  Latitude                        15 non-null     object
 39  Longitude                       15 non-null     object
 40  Location                        15 non-null     object
dtypes: int64(1), object(40)
memory usage: 4.9+ KB

In [52]:
#Export dataset to csv with code below
#nypd_arrests.to_csv('../output/Social_Distancing_Arrests.csv', index=False)

In [53]:
#Find out how many complaints were filed by date
df['Created Date'].value_counts()

04/25/2020 02:41:46 PM    4
04/20/2020 06:03:29 PM    3
05/02/2020 08:22:32 PM    3
05/07/2020 08:28:59 PM    2
04/12/2020 06:49:40 PM    2
                         ..
04/09/2020 06:56:07 PM    1
05/02/2020 10:02:51 PM    1
04/27/2020 01:01:01 PM    1
04/06/2020 08:20:33 PM    1
04/14/2020 09:34:00 PM    1
Name: Created Date, Length: 31201, dtype: int64

In [54]:
#Strip the time element from 'Created Date' column strings
complaint_date = df["Created Date"].map(lambda x: str(x)[:-12])
complaint_date

0        05/10/2020
1        05/09/2020
2        05/09/2020
3        05/09/2020
4        05/09/2020
            ...
31501    03/29/2020
31502    03/29/2020
31503    03/29/2020
31504    03/29/2020
31505    03/29/2020
Name: Created Date, Length: 31506, dtype: object

In [55]:
#Sort our values
complaint_date.value_counts().sort_values(ascending = False).reset_index()

         index  Created Date
0   05/02/2020          1963
1   04/25/2020          1720
2   05/03/2020          1708
3   04/19/2020          1305
4   04/28/2020          1018
5   04/06/2020           963
6   04/20/2020           956
7   05/05/2020           909
8   04/07/2020           873
9   04/14/2020           859
10  04/11/2020           829
11  04/22/2020           828
12  05/07/2020           820
13  04/12/2020           803
14  04/01/2020           792
15  05/01/2020           778
16  03/30/2020           776
17  04/08/2020           750
18  04/23/2020           750
19  04/21/2020           744
20  04/04/2020           694
21  03/31/2020           682
22  05/04/2020           648
23  04/17/2020           628
24  04/09/2020           618
25  04/15/2020           609
26  04/02/2020           607
27  04/05/2020           599
28  04/16/2020           580
29  04/24/2020           565
30  04/18/2020           537
31  04/10/2020           520
32  04/29/2020           488
33  04/13/2020           476
34  05/09/2020           448
35  04/03/2020           436
36  04/26/2020           419
37  04/27/2020           410
38  05/08/2020           407
39  05/06/2020           368
40  04/30/2020           338
41  03/29/2020           262
42  05/10/2020            21
43  03/28/2020             2

In [56]:
#Prepare our data for csv by renaming our indexes
date = complaint_date.value_counts().reset_index().rename(columns = {'index': 'Date', 'Created Date': 'Total Complaints'})
date = date[~date['Date'].str.contains('2019')]
date

          Date  Total Complaints
0   05/02/2020              1963
1   04/25/2020              1720
2   05/03/2020              1708
3   04/19/2020              1305
4   04/28/2020              1018
5   04/06/2020               963
6   04/20/2020               956
7   05/05/2020               909
8   04/07/2020               873
9   04/14/2020               859
10  04/11/2020               829
11  04/22/2020               828
12  05/07/2020               820
13  04/12/2020               803
14  04/01/2020               792
15  05/01/2020               778
16  03/30/2020               776
17  04/08/2020               750
18  04/23/2020               750
19  04/21/2020               744
20  04/04/2020               694
21  03/31/2020               682
22  05/04/2020               648
23  04/17/2020               628
24  04/09/2020               618
25  04/15/2020               609
26  04/02/2020               607
27  04/05/2020               599
28  04/16/2020               580
29  04/24/2020               565
30  04/18/2020               537
31  04/10/2020               520
32  04/29/2020               488
33  04/13/2020               476
34  05/09/2020               448
35  04/03/2020               436
36  04/26/2020               419
37  04/27/2020               410
38  05/08/2020               407
39  05/06/2020               368
40  04/30/2020               338
41  03/29/2020               262
42  05/10/2020                21
43  03/28/2020                 2

In [57]:
#Export dataset to csv with code below
#date.to_csv('../output/Social_Distancing_Complaints_by_date.csv', index=False)

In [58]:
# Top 20 addresses where the most complaints were filed.
df["Incident Address"].value_counts().sort_values(ascending = False).reset_index().head(20)

                     index  Incident Address
0                 BROADWAY               136
1             CENTRAL PARK               121
2     120 WEST   91 STREET                91
3                 5 AVENUE                61
4                 2 AVENUE                61
5                 3 AVENUE                55
6      320 STERLING STREET                54
7                 1 AVENUE                52
8          1705 HOE AVENUE                47
9         AMSTERDAM AVENUE                44
10     1314 MERRIAM AVENUE                44
11           PROSPECT PARK                42
12    150 EAST    2 STREET                39
13      784 JAMAICA AVENUE                39
14           946 47 STREET                38
15               10 AVENUE                37
16  440 ST NICHOLAS AVENUE                37
17  68-03 ROOSEVELT AVENUE                36
18         28-58 32 STREET                34
19                7 AVENUE                34

In [59]:
df[["Incident Address", "Community Board"]]

             Incident Address Community Board
0           355 WEST BROADWAY    02 MANHATTAN
1       1776 LEXINGTON AVENUE    11 MANHATTAN
2        1887 NOSTRAND AVENUE     17 BROOKLYN
3      171-16 HILLSIDE AVENUE       12 QUEENS
4      2228 WHITE PLAINS ROAD        11 BRONX
...                       ...             ...
31501    125 EAST  170 STREET        04 BRONX
31502          5312 16 AVENUE     12 BROOKLYN
31503          4307 18 AVENUE     14 BROOKLYN
31504           4441 BROADWAY    12 MANHATTAN
31505    89-89 UNION TURNPIKE       06 QUEENS

[31506 rows x 2 columns]

In [60]:
# Some streets have the same name and some streets run through multiple community boards;
# Sort the top 20 incident addresses where most complaints were filed and parse by community board.
incident_loc = df.groupby(["Incident Address", "Community Board"])["Incident Address"].count().reset_index(name='count').sort_values(['count'], ascending=False).head(20)
incident_loc

             Incident Address   Community Board  count
17477            CENTRAL PARK      64 MANHATTAN    121
1573     120 WEST   91 STREET      07 MANHATTAN     91
9359      320 STERLING STREET       09 BROOKLYN     54
4389          1705 HOE AVENUE          03 BRONX     47
2241      1314 MERRIAM AVENUE          04 BRONX     44
18364           PROSPECT PARK       55 BROOKLYN     42
3303     150 EAST    2 STREET      03 MANHATTAN     39
15454      784 JAMAICA AVENUE       05 BROOKLYN     39
16831           946 47 STREET       12 BROOKLYN     38
11485  440 ST NICHOLAS AVENUE      10 MANHATTAN     37
17407                BROADWAY      12 MANHATTAN     36
14473  68-03 ROOSEVELT AVENUE         02 QUEENS     36
17404                BROADWAY      07 MANHATTAN     34
8297          28-58 32 STREET         01 QUEENS     34
17198            ASTORIA PARK         01 QUEENS     33
6281         215 BROAD STREET  01 STATEN ISLAND     30
17172        AMSTERDAM AVENUE      07 MANHATTAN     30
7309     2424 HYLAN BOULEVARD  02 STATEN ISLAND     30
15372     770 EASTERN PARKWAY       09 BROOKLYN     28
18144            LENOX AVENUE      10 MANHATTAN     26

In [61]:
#Export dataset to csv with code below
#date.to_csv('../output/Social_Distancing_Complaints_by_address.csv', index=False)